include ../Makefile.common.inc

VERILOG_SOURCES += $(SRC_DIR)/config_regs.v
TOPLEVEL := config_regs
MODULE := test_config_regs

include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim
