include ../Makefile.common.inc

VERILOG_SOURCES += $(RTL_DIR)/config_regs.v
TOPLEVEL := config_regs
MODULE := tb_config_regs

include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim
