include ../Makefile.common.inc

VERILOG_SOURCES += $(SRC_DIR)/config_regs.v
TOPLEVEL := config_regs
MODULE := test_config_regs

include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
